### ISSUE TITLE
Failed to install 'cordova-plugin-in-app-updates' on cordova-android 11.0.0

### ISSUE THREAD

**Issue by Sanjay7878** [andreszs/cordova-plugin-in-app-update#1]
When trying to install the plugin, i am getting an conflict 

Failed to install 'cordova-plugin-in-app-updates': Error: There was a conflict trying to modify attributes with <edit-config> in plugin cordova-plugin-in-app-updates. The conflicting plugin, undefined, already modified the same attributes. The conflict must be resolved before cordova-plugin-in-app-updates can be added. You may use --force to add the plugin and overwrite the conflicting attributes.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/46314540/210944416-b22c5418-ad94-479a-ab73-a9bf76f0998b.png">

**Comment by Denisbelyy** [comment]
Use `cordova plugin add cordova-plugin-in-app-updates --force `it worked for me

**Comment by kriserickson** [comment]
I was getting the same problem and I updated to cordova 12.0.0 and android android 12.0.0 and now I am getting this error.  

Adding --force produces the same error.

```
Failed to install 'cordova-plugin-in-app-updates': TypeError: Cannot read properties of undefined (reading 'id')
    at registerConflict (C:\Projects\quasar\xxx-xxx\src-cordova\node_modules\cordova-android\node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:253:43)
    at C:\Projects\quasar\xxx-xxx\src-cordova\node_modules\cordova-android\node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:278:34
    at Array.forEach (<anonymous>)
    at PlatformMunger._is_conflicting (C:\Projects\quasar\xxx-xxx\src-cordova\node_modules\cordova-android\node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:257:21)
    at PlatformMunger.add_plugin_changes (C:\Projects\quasar\xxx-xxx\src-cordova\node_modules\cordova-android\node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:106:59)
    at C:\Projects\quasar\xxx-xxx\src-cordova\node_modules\cordova-android\node_modules\cordova-common\src\PluginManager.js:120:33
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```


![image](https://github.com/andreszs/cordova-plugin-in-app-updates/assets/325934/5c8bde17-be70-4c52-b4c4-d6a613cacfd4)


I Fixed it by adding 

```xml
<config-file parent="/*" target="res/xml/config.xml">
  <feature name="InAppUpdate">
    <param name="android-package" value="com.andreszs.inappupdate.InAppUpdate" />
  </feature>
</config-file>
```

to the default cordova config.xml in the &lt;platform name="android"&gt;  section

**Comment by andreszs** [comment]
Please try latest version 2.1.0 just released which is 100% working with cordova-android@11 and SDK 32.

Version 2.2.0 to be released soon targets SDK 33 and works with cordova-android@12 perfectly fine as well.

**Comment by boazn0** [comment]
I was getting the same problem and with  cordova 12.0.0 and version 2.2.0  :-/
